// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Hashtbl                 = require("bs-platform/lib/js/hashtbl.js");
var Caml_builtin_exceptions = require("bs-platform/lib/js/caml_builtin_exceptions.js");

function f(n, memo) {
  var result;
  if (n <= 0) {
    result = 0;
  } else if (n <= 2) {
    result = 1;
  } else {
    try {
      result = Hashtbl.find(memo, n);
    }
    catch (exn){
      if (exn === Caml_builtin_exceptions.not_found) {
        var prev = f(n - 1 | 0, memo);
        var secondPrev = f(n - 2 | 0, memo);
        result = prev + secondPrev | 0;
      } else {
        throw exn;
      }
    }
  }
  Hashtbl.add(memo, n, result);
  return result;
}

function fibonacci(n) {
  var memo = Hashtbl.create(/* Some */[/* true */1], n);
  return f(n, memo);
}

exports.f         = f;
exports.fibonacci = fibonacci;
/* No side effect */
